version: "3"
services:
  postgres:
    ports: 
      - 6432:5432 
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jukee
      - POSTGRES_PASSWORD=saifullah
  nginx:
    depends_on:
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    # environment:
    #   - PGUSER=postgres
    #   - PGHOST=localhost
    #   - PGDATABASE=postgres
    #   - PGPASSWORD=iqube
    #   - PGPORT=5432
    env_file: "./server/production.env"
    ports:
      - "5000:5000"
    depends_on: 
     - postgres
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - api


